### ISSUE TITLE
Adding help labels

### ISSUE THREAD

**Issue by daviddavo** [sherlockode/configuration-bundle#64]
If you create a form and you want to add help labels, you'll have to do it manually. It'd be nice to be able to do it in `sherlockode_configuration`, perhaps alongside `label` or inside `options`.

If this is already possible, we could just add it to the README

**Comment by Vowow** [comment]
Hello,

This is not yet possible but could be an interesting feature.
One problem though is that we don't provide any style or JS in the bundle and we are not sure we want to provide one.
If I had to do it in a project, I'll do a form_theme inside my project, not sure if it should be packaged within this bundle.
You can still provide us a Pull request for this one and we'll be happy to review it !

**Comment by daviddavo** [comment]
I tried just adding `help` to the `$baseOptions` and it just works. Symfony's default form themes work fine with it.

https://github.com/sherlockode/configuration-bundle/blob/e860defdd24daef14e63f44ee2b2a37fb0e1803f/Form/Type/ParametersType.php#L36-L43

I will open a PR as soon as I can

**Comment by Vowow** [comment]
This could be done by using options directly in our bundle like this :
`
my_config_field:
    label: parameters.tarte_au_citron_id
    type: simple
    options:
        required: false
        help: 'toto'
`

Could be interesting to give in baseOptions all the options that are inherited in Symfony form components, though.
I'll review the PR and maybe amend to give more options to the user, it's a good idea

**Comment by daviddavo** [comment]
Here's the list of options: https://symfony.com/doc/current/reference/forms/types/form.html#field-options

And here is the code of the `FormType`:

https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Form/Extension/Core/Type/FormType.php

It seems to use an OptionsResolver to handle the options: https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/OptionsResolver/OptionsResolver.php

**Comment by juchi** [comment]
PR has been merged
