### ISSUE TITLE
Allow setting default value in config

### ISSUE THREAD

**Issue by daviddavo** [sherlockode/configuration-bundle#66]
I know that it is possible to set a default value passing a second parameter to the `get` function, but it's impossible to get default values with `getAll`. Furthermore, you either need to create a wrapper Service, or set the default parameter multiple times.

I think it would be great if it was possible to define the default parameters in the `.yml` file (if you want), and then the value would be returned with `getAll`, or `get` with second input set to `null`.

A third way of doing it would be populating the ddbb if it's not already populated, perhaps with a doctirne fixture. But it is also duplicating the site where you define the parameters, and prone to errors.

**Comment by Vowow** [comment]
The second solution seems good for the simple choices such as simple, checkbox, choice.... And it could be good to put it in yaml
However I don't see any use case in real life that you can have to get all default value in `getAll` but why not, less is more.
Don't hesitate to provide a PR on this one

**Comment by daviddavo** [comment]
In my case, the problem arose when I wanted to create a form, and I used `getAll()`. All values are unpopulated and the only way to solve it would be to "get the default value" of the ones that are not defined. I'd have to also define these values every time I use `get`

**Comment by juchi** [comment]
@daviddavo while I understand the use case to have a default value populated, I'm not sure that a default value in the yaml configuration is the best approach. Why not using a fixture as you suggested ? (or going with the migration script)
As is, the getAll() will return all default values alongside user values, so when the parameter form is saved, all default value will be saved in DB as well, so we have the same result as with a fixture/migration.
Am I missing some use case you have here ?

**Comment by Vowow** [comment]
This is merged, thank's
