### ISSUE TITLE
The controller for URI "/parameter" is not callable: Controller "sherlockode_configuration.controller.parameter:listAction" does neither exist as service nor as class.

### ISSUE THREAD

**Issue by pixiekat** [sherlockode/configuration-bundle#80]
From [#79](https://github.com/sherlockode/configuration-bundle/issues/79).

Using Symfony 6.3 and when I ping /parameter, the above error occurs. I can see all three routes in `php bin/console debug:router` though. 

```
sherlockode_configuration.parameters   ANY      ANY      ANY    /parameter
sherlockode_configuration.export       ANY      ANY      ANY    /parameters/export
sherlockode_configuration.import       ANY      ANY      ANY    /parameters/import
```

**Comment by NeilPeyssard** [comment]
There was an error in the routing declaration. I have opened a PR to fix it.

As a quick workaround, if you can't wait for a new tag, you can override the default routing.

**Comment by Vowow** [comment]
New release with this fix : https://github.com/sherlockode/configuration-bundle/releases/tag/v0.6.0

**Comment by Vowow** [comment]
https://github.com/sherlockode/configuration-bundle/releases/tag/v0.6.0
