### ISSUE TITLE
Symfony 7.0 support

### ISSUE THREAD

**Issue by pszewczykpl** [sherlockode/configuration-bundle#83]
Hi,

I think we should refactor the code to eliminate all deprecations and prepare for Symfony 7.0 support.
What do you think about this?

Currently I found the following deprecations:
`Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "Sherlockode\ConfigurationBundle\Command\ExportCommand" class instead`

`Since symfony/console 6.1: Relying on the static property "$defaultDescription" for setting a command description is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "Sherlockode\ConfigurationBundle\Command\ExportCommand" class instead.`

`Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "Sherlockode\ConfigurationBundle\Command\ImportCommand" class instead.`

`Since symfony/console 6.1: Relying on the static property "$defaultDescription" for setting a command description is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "Sherlockode\ConfigurationBundle\Command\ImportCommand" class instead.`

`Method "Symfony\Component\DependencyInjection\Extension\ExtensionInterface::load()" might add "void" as a native return type declaration in the future. Do the same in implementation "Sherlockode\ConfigurationBundle\DependencyInjection\SherlockodeConfigurationExtension" now to avoid errors or add an explicit @return annotation to suppress this message.`

`Method "Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface::process()" might add "void" as a native return type declaration in the future. Do the same in implementation "Sherlockode\ConfigurationBundle\DependencyInjection\Compiler\FieldTypePass" now to avoid errors or add an explicit @return annotation to suppress this message.`

`Method "Symfony\Component\Form\AbstractType::buildForm()" might add "void" as a native return type declaration in the future. Do the same in child class "Sherlockode\ConfigurationBundle\Form\Type\ParametersType" now to avoid errors or add an explicit @return annotation to suppress this message.`

`Method "Symfony\Component\Form\AbstractType::buildForm()" might add "void" as a native return type declaration in the future. Do the same in child class "Sherlockode\ConfigurationBundle\Form\Type\ImageType" now to avoid errors or add an explicit @return annotation to suppress this message.`

`Method "Symfony\Component\Form\AbstractType::configureOptions()" might add "void" as a native return type declaration in the future. Do the same in child class "Sherlockode\ConfigurationBundle\Form\Type\ImageType" now to avoid errors or add an explicit @return annotation to suppress this message.`

`Method "Symfony\Component\Form\AbstractType::buildView()" might add "void" as a native return type declaration in the future. Do the same in child class "Sherlockode\ConfigurationBundle\Form\Type\ImageType" now to avoid errors or add an explicit @return annotation to suppress this message.`

`Method "Symfony\Component\Form\AbstractType::buildForm()" might add "void" as a native return type declaration in the future. Do the same in child class "Sherlockode\ConfigurationBundle\Form\Type\ImportType" now to avoid errors or add an explicit @return annotation to suppress this message.`

`User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "Sherlockode\ConfigurationBundle\SherlockodeConfigurationBundle" now to avoid errors or add an explicit @return annotation to suppress this message.`

In most cases you should add void, however, for commands Symfony recommends the following:
**The static property $defaultDescription was deprecated in Symfony 6.1. Instead, use the #[AsCommand] attribute to define the optional command description.**
_Symfony docs (7.0): https://symfony.com/doc/current/console.html
Symfony docs (6.4): https://symfony.com/doc/6.4/console.html_

Of course, we currently have support for PHP versions lower than 8.0 (where attributes were introduced), so I think it is time to only support PHP above version 8.
If there is agreement on the above, I could refactor project to support Symfony 7.0 - it would be a very good step forward for the project.

**Comment by Vowow** [comment]
This issue has been corrected & tagged
Thank you for your work
